# Generated by Django 5.0.6 on 2026-04-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="active_plan",
            field=models.CharField(
                choices=[("free", "Free"), ("pro", "Pro"), ("team", "Team")],
                default="free",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="billing_status",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("active", "Active"),
                    ("trialing", "Trialing"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("incomplete", "Incomplete"),
                    ("unpaid", "Unpaid"),
                ],
                default="free",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="onboarding_api_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
