# Generated by Django 5.0.6 on 2026-04-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0003_teamworkspace_teammembership_teaminvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="billing_issue_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="last_invoice_status",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="last_payment_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="next_payment_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
