# Generated by Django 5.0.6 on 2025-08-13 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=255, unique=True)),
                ("api_key", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="processes.host",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.IntegerField()),
                ("ppid", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=512)),
                ("cpu_percent", models.FloatField(blank=True, null=True)),
                ("memory_mb", models.FloatField(blank=True, null=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="processes.snapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["snapshot"], name="processes_p_snapsho_d6896a_idx"
                    ),
                    models.Index(
                        fields=["pid", "ppid"], name="processes_p_pid_a95440_idx"
                    ),
                ],
            },
        ),
    ]
