# Generated by Django 5.0.6 on 2026-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0003_host_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="host",
            options={"ordering": ["hostname"]},
        ),
        migrations.AlterModelOptions(
            name="process",
            options={"ordering": ["-cpu_percent", "-memory_mb", "name"]},
        ),
        migrations.AddField(
            model_name="host",
            name="agent_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="host",
            name="agent_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="host",
            name="cpu_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="host",
            name="device_type",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="host",
            name="latest_alert_level",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="host",
            name="primary_ip",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="host",
            name="risk_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="host",
            name="total_disk_gb",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="host",
            name="total_memory_mb",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="active_user_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="listening_ports",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="load_fifteen",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="load_five",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="load_one",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="network_recv_mb",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="network_sent_mb",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="host",
            name="hostname",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
