# Generated by Django 5.0.6 on 2026-04-01 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0005_alert_alertauditlog_alertrulesettings_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                ("slack_enabled", models.BooleanField(default=False)),
                ("slack_webhook_url", models.URLField(blank=True)),
                ("webhook_enabled", models.BooleanField(default=False)),
                ("webhook_url", models.URLField(blank=True)),
                ("notify_info", models.BooleanField(default=False)),
                ("notify_warning", models.BooleanField(default=True)),
                ("notify_critical", models.BooleanField(default=True)),
                ("notify_offline", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=16,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("destination", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("response_excerpt", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_deliveries",
                        to="processes.alert",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_deliveries",
                        to="processes.host",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["host", "channel"],
                        name="processes_n_host_id_440d6b_idx",
                    ),
                    models.Index(
                        fields=["event_type", "status"],
                        name="processes_n_event_t_04dfdf_idx",
                    ),
                ],
            },
        ),
    ]
