# Generated by Django 5.0.6 on 2026-04-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0006_notificationpreference_notificationdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="network_connections",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="startup_items",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
