# Generated by Django 5.0.6 on 2026-04-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0007_snapshot_network_connections_snapshot_startup_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrulesettings",
            name="new_software_tracking_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alertrulesettings",
            name="remote_session_tracking_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alertrulesettings",
            name="startup_drift_tracking_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alertrulesettings",
            name="unsigned_software_alert_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="software_inventory",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="user_sessions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
