# Generated by Django 5.0.6 on 2026-04-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0008_alertrulesettings_new_software_tracking_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrulesettings",
            name="auth_event_tracking_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alertrulesettings",
            name="file_integrity_tracking_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="auth_events",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="file_integrity_items",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
