# Generated by Django 5.0.6 on 2026-04-01 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0009_alertrulesettings_auth_event_tracking_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="collector_sources",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="file_events",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="HostEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(db_index=True, max_length=32)),
                ("kind", models.CharField(db_index=True, max_length=64)),
                ("severity", models.CharField(db_index=True, max_length=16)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="processes.host",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="processes.snapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["host", "occurred_at"],
                        name="processes_h_host_id_22742f_idx",
                    ),
                    models.Index(
                        fields=["host", "category"],
                        name="processes_h_host_id_b00930_idx",
                    ),
                    models.Index(
                        fields=["host", "kind"], name="processes_h_host_id_b95b2d_idx"
                    ),
                ],
            },
        ),
    ]
