# Generated by Django 5.0.6 on 2026-04-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0010_snapshot_collector_sources_snapshot_file_events_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="exe_path",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="process",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="dns_events",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="process_events",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="security_posture",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="service_inventory",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
