# Generated by Django 5.0.6 on 2026-04-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0011_process_exe_path_process_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="network_events",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
