# Generated by Django 5.0.6 on 2026-04-02 07:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0012_snapshot_network_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrulesettings",
            name="minimum_mobile_battery_percent",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="alertrulesettings",
            name="minimum_mobile_os_version",
            field=models.CharField(blank=True, default="17", max_length=32),
        ),
        migrations.AddField(
            model_name="alertrulesettings",
            name="mobile_compliance_tracking_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alertrulesettings",
            name="policy_engine_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alertrulesettings",
            name="vulnerability_tracking_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="SavedCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("mobile", "Mobile"),
                            ("vulnerability", "Vulnerability"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("builtin", models.BooleanField(default=False)),
                ("evaluator", models.CharField(db_index=True, max_length=64)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="SavedCheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("warn", "Warn"),
                            ("fail", "Fail"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_results",
                        to="processes.host",
                    ),
                ),
                (
                    "saved_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="processes.savedcheck",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_results",
                        to="processes.snapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("refresh_snapshot", "Refresh snapshot"),
                            ("terminate_process", "Terminate process"),
                            ("collect_diagnostics", "Collect diagnostics"),
                            ("live_query", "Live query"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_actions",
                        to="processes.alert",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_actions",
                        to="processes.host",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_agent_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_actions",
                        to="processes.snapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["host", "status"], name="processes_a_host_id_f24aa1_idx"
                    ),
                    models.Index(
                        fields=["kind", "status"], name="processes_a_kind_5e624c_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="savedcheck",
            constraint=models.UniqueConstraint(
                fields=("user", "slug"), name="unique_saved_check_slug_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="savedcheckresult",
            index=models.Index(
                fields=["host", "status"], name="processes_s_host_id_d62a00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedcheckresult",
            index=models.Index(
                fields=["saved_check", "created_at"],
                name="processes_s_saved_c_a7218f_idx",
            ),
        ),
    ]
